
#load "Utils.jai";
#load "Approx.jai";

#load "Elementary.jai";
#load "Complex.jai";
#load "Polynomials.jai";
#load "Approximations.jai";

#load "Types.jai";
#load "Scalar.jai";
#load "VectorTypes.jai";
#load "Vector.jai";
#load "MatrixTypes.jai";
#load "Matrix.jai";
#load "Checks.jai";
#load "LinearAlgebra.jai";

CHECKS :: true;


#scope_module

#import "Basic";
Math   :: #import "Math";
Pool   :: #import "Pool";
String :: #import "String";